[package]
name = "day_09"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.7"
hashbrown = "0.13.1"
nalgebra = "0.31.4"
atoi = "2"
rustc-hash = "1.1"
